# Generated by Django 5.2.7 on 2025-10-27 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("students", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("O", "O Level"), ("A", "A Level")],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="approved_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="departments", to="classes.subject"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="template",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="department",
            name="template_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periods_per_week",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
                ("is_compulsory", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in class timetable"
                    ),
                ),
                (
                    "room_preference",
                    models.CharField(
                        blank=True,
                        help_text="Preferred room for this subject",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                # teacher_in_charge will be added in a follow-up migration
            ],
        ),
        migrations.CreateModel(
            name="DisciplineIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateField()),
                ("description", models.TextField()),
                ("repeated_offense", models.BooleanField(default=False)),
                ("alert_sent", models.BooleanField(default=False)),
                # reported_by FK deferred to follow-up migration
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_incidents",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("available", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_books",
                        to="classes.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("overdue", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_issues",
                        to="students.student",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="classes.librarybook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="students.student",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="classes.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., S.1, S.2, S.3, etc.", max_length=20
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("A", "Section A"),
                            ("B", "Section B"),
                            ("C", "Section C"),
                            ("D", "Section D"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARTS", "Arts"),
                            ("SCIENCE", "Science"),
                            ("COMMERCIAL", "Commercial"),
                            ("GENERAL", "General"),
                            ("TECHNICAL", "Technical"),
                        ],
                        help_text="Specialization track for A-Level classes",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "current_student_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, help_text="Primary classroom", max_length=20
                    ),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "class_average",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "performance_rating",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Good"),
                            ("C", "Average"),
                            ("D", "Below Average"),
                            ("F", "Poor"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "attendance_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall class attendance percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "discipline_rating",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Good"),
                            ("C", "Average"),
                            ("D", "Needs Improvement"),
                            ("F", "Poor"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2024/2025", help_text="e.g., 2024/2025", max_length=9
                    ),
                ),
                (
                    "term",
                    models.PositiveIntegerField(
                        choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")], default=1
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(default="08:00", help_text="Class start time"),
                ),
                (
                    "end_time",
                    models.TimeField(default="14:00", help_text="Class end time"),
                ),
                (
                    "break_time",
                    models.TimeField(default="10:30", help_text="Break time"),
                ),
                ("has_projector", models.BooleanField(default=False)),
                ("has_computers", models.BooleanField(default=False)),
                ("has_laboratory_access", models.BooleanField(default=False)),
                ("has_library_access", models.BooleanField(default=True)),
                (
                    "special_equipment",
                    models.TextField(
                        blank=True,
                        help_text="Special equipment available for this class",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_full", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_target",
                    models.FloatField(
                        default=75.0,
                        help_text="Target average score for the class",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "attendance_target",
                    models.FloatField(
                        default=90.0,
                        help_text="Target attendance rate",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "promotion_rate_target",
                    models.FloatField(
                        default=95.0,
                        help_text="Target promotion rate to next class",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assistant_class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_class_teacher_of",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_teacher_of",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "compulsory_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compulsory_for_classes",
                        to="classes.subject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elective_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="elective_for_classes",
                        to="classes.subject",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="classes.level",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="classes",
                        through="classes.ClassSubject",
                        to="classes.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["level", "name", "section"],
            },
        ),
        migrations.AddField(
            model_name="classsubject",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classes.schoolclass"
            ),
        ),
        migrations.CreateModel(
            name="ClassResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("resource_file", models.FileField(upload_to="class_resources/")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("NOTES", "Notes"),
                            ("ASSIGNMENT", "Assignment"),
                            ("REFERENCE", "Reference"),
                            ("SYLLABUS", "Syllabus"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_visible_to_students", models.BooleanField(default=True)),
                # uploaded_by FK deferred to follow-up migration
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="classes.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("venue", models.CharField(blank=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic"),
                            ("SPORTS", "Sports"),
                            ("CULTURAL", "Cultural"),
                            ("MEETING", "Meeting"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                # organizer FK deferred to follow-up migration
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="classes.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["event_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ClassArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="classes.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="classes.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                # class_teacher FK deferred to follow-up migration
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="classes.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("attendance_marked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classes.subject",
                    ),
                ),
                # lecture.teacher FK deferred to follow-up migration
                (
                    "resources",
                    models.ManyToManyField(blank=True, to="classes.resource"),
                # ClassEvent.organizer FK deferred to follow-up migration
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lectures",
                        to="classes.stream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("present", models.BooleanField(default=True)),
                ("term", models.CharField(blank=True, max_length=20)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_reports",
                        to="students.student",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.stream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achievement", models.CharField(blank=True, max_length=200)),
                ("participation_date", models.DateField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="classes.club",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("period_label", models.CharField(blank=True, max_length=50)),
                ("room", models.CharField(blank=True, max_length=50)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="classes.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classes.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LectureAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("present", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="classes.lecture",
                    ),
                ),
                # LectureAttendance.marked_by FK deferred to follow-up migration
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_attendances",
                        to="students.student",
                    # Timetable.teacher FK deferred to follow-up migration
            model_name="schoolclass",
            index=models.Index(
                fields=["level", "name"], name="classes_sch_level_i_4d7d6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["academic_year", "term"], name="classes_sch_academi_416c16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["class_teacher"], name="classes_sch_class_t_46831e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["is_active"], name="classes_sch_is_acti_cfb6a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together={("name", "level", "section", "academic_year", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("school_class", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={
                ("school_class", "stream", "day", "start_time", "end_time")
            },
        ),
    ]
