# Generated by Django 5.2.7 on 2025-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="School Name", max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school/logo/"),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="school/hero/"),
                ),
                ("about_text", models.TextField(blank=True)),
                ("features", models.TextField(blank=True)),
            ],
        ),
    ]
