# Generated by Django 5.2.7 on 2025-10-21 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Removed explicit dependency on classes.__first__ to avoid circular migration
    # The teachers initial migration was applied earlier; in this dev environment
    # it's safe to omit the forward dependency so `classes` migrations can run.
    dependencies = [
        ("classes", "0002_level_section_department_approved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="classes.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("CAT", "Continuous Assessment Test"),
                            ("END_TERM", "End of Term Exam"),
                            ("PRACTICAL", "Practical Exam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classes.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classes.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_groups_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(related_name="groups", to="classes.subject"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=30, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="teachers/photos/"
                    ),
                ),
                ("emergency_contact", models.CharField(blank=True, max_length=100)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Teacher", "Teacher"),
                            ("Class Teacher", "Class Teacher"),
                            ("Subject Teacher", "Subject Teacher"),
                            ("HOD", "Head of Department"),
                        ],
                        default="Teacher",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contractual", "Contractual"),
                        ],
                        default="Full-time",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("On Leave", "On Leave"),
                            ("Retired", "Retired"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("qualifications", models.TextField(blank=True)),
                ("specializations", models.CharField(blank=True, max_length=100)),
                ("lesson_plans", models.TextField(blank=True)),
                ("teaching_resources", models.TextField(blank=True)),
                ("assessments_notes", models.TextField(blank=True)),
                ("grades", models.TextField(blank=True)),
                ("attendance_record", models.TextField(blank=True)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_class_teacher", models.BooleanField(default=False)),
                ("committees", models.CharField(blank=True, max_length=200)),
                ("clubs_notes", models.CharField(blank=True, max_length=200)),
                ("event_organization", models.TextField(blank=True)),
                ("student_mentoring", models.TextField(blank=True)),
                ("community_service", models.TextField(blank=True)),
                ("portal_access", models.BooleanField(default=True)),
                ("notifications", models.TextField(blank=True)),
                ("parent_communication", models.TextField(blank=True)),
                ("analytics_access", models.BooleanField(default=True)),
                ("performance_records", models.TextField(blank=True)),
                (
                    "exam_pass_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "class_average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("professional_development", models.TextField(blank=True)),
                ("recognition_awards", models.TextField(blank=True)),
                ("syllabus_coverage_analytics", models.TextField(blank=True)),
                ("examination_oversight", models.TextField(blank=True)),
                ("multi_role_support", models.BooleanField(default=False)),
                ("digital_archive", models.TextField(blank=True)),
                (
                    "assessments",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="teachers.assessment"
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_teachers",
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "clubs",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="classes.club"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="classes.department",
                    ),
                ),
                (
                    "streams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_teachers",
                        to="classes.stream",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_teachers",
                        to="classes.subject",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_records",
                to="teachers.teacher",
            ),
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("period", models.CharField(max_length=10)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="classes.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "day", "period", "stream")},
            },
        ),
    ]
